# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :box_version => "1902.01",
        :net => [
                   {ip: '192.168.1.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "net"},
                ]
  },
  :client => {
        :box_name => "centos/7",
        :box_version => "1902.01",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "net"},
                ]
  },

  }


Vagrant.configure("2") do |config|

### Coonfigure shared folders between host and guest VM
# config.vm.synced_folder "share/", "/mnt/share"

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

	box.vm.provider :virtualbox do |vb|
	  vb.customize ["modifyvm", :id, "--memory", "256"]
	  vb.customize ["modifyvm", :id, "--audio", "none"]
	end

	if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        case boxname.to_s
        when "server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL

          sudo su &&
          groupadd admin && useradd admin -g admin &&
          groupadd testuser && useradd testuser -g testuser &&
          groupadd newroot && useradd newroot -g newroot &&
          echo "adminpass" | passwd admin --stdin &&
          echo "testuserpass" | passwd testuser --stdin &&
          echo "newrootpass" | passwd newroot --stdin &&
          sed -i '101inewroot    ALL=(ALL)       ALL' /etc/sudoers
          lid -g admin | awk 'BEGIN{FS="("} {print $1}' > /usr/local/etc/pam_permited_users.txt &&
          sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config &&
          systemctl restart sshd &&
          yum install wget -y &&
          cd /usr/local/bin &&
          wget https://raw.githubusercontent.com/glmonarch/otus.ru-Linux_administration/master/LAB10/login_check.sh &&
	        chmod 777 /usr/local/bin/login_check.sh &&
          sed -i '2iaccount    required     pam_exec.so /usr/local/bin/login_check.sh' /etc/pam.d/sshd &&
	        whoami


            SHELL
        when "client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL


            SHELL

          end
         end
        end

end
